### ISSUE TITLE
Feature request -- Add functionality to Linked_list

### ISSUE THREAD

**Issue by dheater** [nasa/libSPRITE#3]
Suggest an `isEmpty()` method on Linked_list:

    bool Linked_list::isEmpty()
    {
       return m_head == NULL;
    }

I didn't see one (sorry if it's already there), and it makes the code that uses Linked_list a little cleaner. 

I'd also like to see something like a `pop_front()` and `pop_back()` that retrieve and remove the corresponding element in one shot. It'd give the Linked_list both queue and stack like capability.

**Comment by dheater** [comment]
Added `is_empy()` function to the linked list. Commit: 1f2f607049f9dbc61a61e946bb1e3b48625f8e70

**Comment by dheater** [comment]
The pop functions are a bit more tricky. Because at the end of the operation, the node is deleted, the data must be copied to be returned to the user.

I don't want to allocate memory to return within the pop function, because it then becomes the users responsibility to free that memory. Such memory ownership transfers easily become memory leaks.

I can accept a parameter from the user to the `pop()` function and copy the node data into it. If I pass by reference, and the list is empty, I need a return code to let the user know the returned value is invalid. I can use a pointer parameter and return NULL if the list is empty, but then I can't be sure that the user allocated memory for the pointer or just declared a pointer and passed it in expecting me to return a pointer to the data. Neither option is without fault, Suggestions?

**Comment by simulated** [comment]
I think this gives me everything I want. It's what I'm doing now, outside the class. It allows expressions like:  

   if (pop_front(nextItem)) { ... }

bool pop_front(T& userdata)
{
   if (head())
   {
      userdata = head()->data;
      delete_front();
      return true;
   }
   return false;
}

**Comment by dheater** [comment]
Committed requested changes.
